[pytest]
pythonpath = .
# Главная папка с тестами (внутри могут быть любые подпапки)
testpaths = src/tests
# Имена тестовых файлов
python_files = test_*.py *_test.py
# Имена классов
python_classes = Test* *Test
# Имена методов:
python_functions = test_* *_test
# Маркеры
markers =
    api: API test
    ui: UI test
    debug: Debug test
# для вывода логов в консоль где надо
    log_http: enable HTTP logging
# ⚙️ Опции запуска (verbose всегда включен)
addopts = -v
